server:
  port: 8082
spring:
  application:
    name: key
  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: komapperadmin
    password: komapper1!2@
axon:
  serializer:
    general: xstream
  axonserver:
    servers: 127.0.0.1:8124
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
