server:
  port: 8081
spring:
  application:
    name: mail
  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: komapperadmin
    password: komapper1!2@
  mail:
    host: smtp.worksmobile.com
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: false
            required: true
          ssl:
            enable: true
          protocol: TLSv1.2
          connectiontimeout: 5000
    username: komapperdev@komapper.ai
    password: qT5QrCiD63fM

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true 
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
axon:
  axonserver:
    servers: 127.0.0.1:8124
  serializer:
    general: xstream
    axonserver:
      servers: 127.0.0.1:8124
      client-id: mail
      component-name: mail-component
